

#FosUserBundle Route
# SECURITY
fos_user_security_login:
    path: /login
    defaults: { _controller: UserBundle:Security:login }

fos_user_security_check:
    path: /login/check
    defaults: { _controller: UserBundle:Security:check }

# REGISTRATION
fos_user_registration_register:
    path: /register
    defaults: { _controller: UserBundle:Registration:register }

# RESETTING PASSWORD
fos_user_resetting_request:
    path: /mot-de-passe-oublie/reinitialisation
    defaults: { _controller: FOSUserBundle:Resetting:request }


fos_user_resetting_send_email:
    path: /mot-de-passe-oublie/e-mail
    defaults: { _controller: FOSUserBundle:Resetting:sendEmail }


fos_user_resetting_reset:
    path: /mot-de-passe-oublie/{token}
    defaults: { _controller: FOSUserBundle:Resetting:reset }

# PROFILE
fos_user_profile_show:
    path: /profile
    defaults: { _controller: FOSUserBundle:Profile:show }

fos_user_profile_edit:
    path: /profile/edit
    defaults: { _controller: FOSUserBundle:Profile:edit }


# HWIOAuthBundle
hwi_oauth_redirect:
    resource: "@HWIOAuthBundle/Resources/config/routing/redirect.xml"
    prefix:   /connect

hwi_oauth_login:
    resource: "@HWIOAuthBundle/Resources/config/routing/login.xml"
    prefix:   /login

facebook_login:
    path: /login/check-facebook

google_login:
    path: /login/check-google

twitter_login:
    path: /login/check-twitter







